CREATE TABLE IF NOT EXISTS `CUSTOMERS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `AGE` int(11) NOT NULL,
  `COUNTRY` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `CUSTOMER_ITEMS` (
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `ITEM` varchar(100) NOT NULL,
  KEY `fk_inv_customer_id` (`CUSTOMER_ID`),
  CONSTRAINT `fk_inv_customer_id` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `CUSTOMER_STATUS` (
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `STATUS` varchar(100) NOT NULL,
  KEY `fk_inv_stus_customer_id` (`CUSTOMER_ID`),
  CONSTRAINT `fk_inv_stus_customer_id` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;